-- Performance indexes for production scale
-- Generated by Principal Architect Audit - January 04, 2026
-- Run with: npx drizzle-kit push OR apply directly to database

-- High-priority indexes (critical for performance at scale)

-- Vault Ledger Entries - heavily queried by user
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_vault_ledger_user_id 
  ON vault_ledger_entries(user_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_vault_ledger_created_at 
  ON vault_ledger_entries(created_at DESC);

-- Combined index for common query pattern (user + time range)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_vault_ledger_user_created 
  ON vault_ledger_entries(user_id, created_at DESC);

-- Transactions - frequent queries by user and status
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactions_user_id 
  ON transactions(user_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactions_status 
  ON transactions(status);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactions_created_at 
  ON transactions(created_at DESC);

-- Combined index for admin transaction views
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactions_status_created 
  ON transactions(status, created_at DESC);

-- BNSL Plans - queried by user and status
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_bnsl_plans_user_id 
  ON bnsl_plans(user_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_bnsl_plans_status 
  ON bnsl_plans(status);

-- Audit Logs - queried by entity for viewing history
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_logs_entity 
  ON audit_logs(entity_type, entity_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_logs_timestamp 
  ON audit_logs(timestamp DESC);

-- Medium-priority indexes (add before high load)

-- KYC Submissions
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_kyc_submissions_user 
  ON kyc_submissions(user_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_kyc_submissions_status 
  ON kyc_submissions(status);

-- Trade Cases (FinaBridge)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_trade_cases_user 
  ON trade_cases(user_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_trade_cases_status 
  ON trade_cases(status);

-- Certificates
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_certificates_user 
  ON certificates(user_id);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_certificates_status 
  ON certificates(status);

-- Approval Queue - frequently filtered by status
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_approval_queue_status 
  ON approval_queue(status);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_approval_queue_created 
  ON approval_queue(created_at DESC);

-- System Logs - for monitoring and debugging
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_system_logs_level 
  ON system_logs(level);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_system_logs_created 
  ON system_logs(created_at DESC);

-- Vault Ownership Summary - critical for balance lookups
-- (Already has unique constraint on user_id, but add for safety)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_vault_ownership_user 
  ON vault_ownership_summary(user_id);

-- Deposit/Withdrawal Request queues
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_deposit_requests_status 
  ON deposit_requests(status);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_withdrawal_requests_status 
  ON withdrawal_requests(status);

-- AML Cases - for compliance dashboard
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_aml_cases_status 
  ON aml_cases(status);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_aml_cases_user 
  ON aml_cases(user_id);
