// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/exporter-dashboard/InstitutionalTrader.tsx": () => import("../components/mockups/exporter-dashboard/InstitutionalTrader.tsx"),
  "./components/mockups/exporter-dashboard/OperationsCockpit.tsx": () => import("../components/mockups/exporter-dashboard/OperationsCockpit.tsx"),
  "./components/mockups/exporter-dashboard/PremiumFintech.tsx": () => import("../components/mockups/exporter-dashboard/PremiumFintech.tsx"),
  "./components/mockups/glass-themes/CreamLight.tsx": () => import("../components/mockups/glass-themes/CreamLight.tsx"),
  "./components/mockups/glass-themes/DarkRedbrick.tsx": () => import("../components/mockups/glass-themes/DarkRedbrick.tsx"),
  "./components/mockups/glass-themes/LightRedbrick.tsx": () => import("../components/mockups/glass-themes/LightRedbrick.tsx"),
  "./components/mockups/glass-themes/MidRedbrick.tsx": () => import("../components/mockups/glass-themes/MidRedbrick.tsx"),
  "./components/mockups/exporter-dashboard/InstitutionalTrader.tsx": () => import("../components/mockups/exporter-dashboard/InstitutionalTrader.tsx"),
  "./components/mockups/exporter-dashboard/OperationsCockpit.tsx": () => import("../components/mockups/exporter-dashboard/OperationsCockpit.tsx"),
  "./components/mockups/exporter-dashboard/PremiumFintech.tsx": () => import("../components/mockups/exporter-dashboard/PremiumFintech.tsx"),
  "./components/mockups/settlement-section/CommandTerminal.tsx": () => import("../components/mockups/settlement-section/CommandTerminal.tsx"),
  "./components/mockups/settlement-section/DashboardControl.tsx": () => import("../components/mockups/settlement-section/DashboardControl.tsx"),
  "./components/mockups/settlement-section/GatePipeline.tsx": () => import("../components/mockups/settlement-section/GatePipeline.tsx"),
  "./components/mockups/settlement-section/NarrativeEditorial.tsx": () => import("../components/mockups/settlement-section/NarrativeEditorial.tsx"),
  "./components/mockups/settlement-section/RiskScorecard.tsx": () => import("../components/mockups/settlement-section/RiskScorecard.tsx"),
  "./components/mockups/settlement-section/SwimlanMap.tsx": () => import("../components/mockups/settlement-section/SwimlanMap.tsx"),
  "./components/mockups/settlement-section/TimelineFlow.tsx": () => import("../components/mockups/settlement-section/TimelineFlow.tsx")
};
