// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-layouts/CommandCenter.tsx": () => import("../components/mockups/dashboard-layouts/CommandCenter.tsx"),
  "./components/mockups/dashboard-layouts/CompactDense.tsx": () => import("../components/mockups/dashboard-layouts/CompactDense.tsx"),
  "./components/mockups/dashboard-layouts/MagazineEditorial.tsx": () => import("../components/mockups/dashboard-layouts/MagazineEditorial.tsx")
};
