// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/settlement-section/DashboardControl.tsx": () => import("../components/mockups/settlement-section/DashboardControl.tsx"),
  "./components/mockups/settlement-section/NarrativeEditorial.tsx": () => import("../components/mockups/settlement-section/NarrativeEditorial.tsx"),
  "./components/mockups/settlement-section/TimelineFlow.tsx": () => import("../components/mockups/settlement-section/TimelineFlow.tsx")
};
