import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key
});

// Translation dictionary
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.finavault': 'FinaVault',
    'nav.finapay': 'FinaPay',
    'nav.finabridge': 'FinaBridge',
    'nav.bnsl': 'BNSL',
    'nav.joinUs': 'About Us',
    'nav.personal': 'Personal',
    'nav.business': 'Business',
    
    // Hero Section
    'hero.finatrades': 'Finatrades',
    'hero.personal.title': 'Digital Gold, Designed for Everyday People',
    'hero.personal.subtitle': 'Save, store, and use real gold value through a secure, modern online account.',
    'hero.personal.description': "Finatrades gives you the power of gold — send, receive, spend anywhere, and earn more through BNSL. Optional: Join structured B'N'SL plans — lock gold into structured buy back plans for defined durations.",
    'hero.personal.cta1': 'About Us',
    'hero.personal.cta2': 'Create Finatrades Account',
    'hero.business.title': 'Regulated Gold-Backed Financial Infrastructure',
    'hero.business.subtitle': 'Designed for corporates, importers, exporters, trading houses, and institutional partners.',
    'hero.business.description': 'Thanks to a strategic partnership with Wingold and Metals DMCC, Finatrades transforms physical gold into a settlement-ready financial instruments.',
    'hero.business.cta1': 'About Us',
    'hero.business.cta2': 'Create Finatrades Account',
    'hero.swissRegulated': 'Swiss-Regulated Platform',
    
    // Products
    'products.title': 'Our Products',
    'products.subtitle': 'A complete suite of gold-backed financial tools',
    'products.explore': 'Explore',
    
    // Personal Products
    'products.personal.finavault.name': 'FinaVault',
    'products.personal.finavault.tagline': 'Personal Gold Locker',
    'products.personal.finavault.description': 'A secure digital ledger showing your stored gold, certificates, and purity details.',
    'products.personal.finapay.name': 'FinaPay Wallet',
    'products.personal.finapay.tagline': 'Gold Value View',
    'products.personal.finapay.description': 'Displays your gold in grams and estimated value. Helps plan expenses and savings.',
    'products.personal.bnsl.name': 'FinaEarn (BNSL)',
    'products.personal.bnsl.tagline': 'Buy Back Plans',
    'products.personal.bnsl.description': 'Choose defined durations (12, 24, or 36 months) for structured buy back.',
    
    // Business Products
    'products.business.finavault.name': 'FinaVault Corporate',
    'products.business.finavault.tagline': 'Corporate Gold Reserve Ledger',
    'products.business.finavault.description': 'Complete visibility across bar numbers, batch origins, purity, and vault locations.',
    'products.business.finapay.name': 'FinaPay Business',
    'products.business.finapay.tagline': 'Operational Gold Dashboard',
    'products.business.finapay.description': 'Real-time value tracking for treasury, risk monitoring, and allocation.',
    'products.business.finabridge.name': 'FinaBridge',
    'products.business.finabridge.tagline': 'Trade Support Layer',
    'products.business.finabridge.description': 'Documentation and workflows that support trade deals backed by gold value.',
    'products.business.bnsl.name': 'FinaEarn (BNSL)',
    'products.business.bnsl.tagline': 'Programmatic Buy Back',
    'products.business.bnsl.description': 'Lock gold into structured terms aligned with business cycles.',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.titleBusiness': 'How It Works for Business',
    'howItWorks.subtitle': 'A simple journey from account creation to gold-backed wealth.',
    'howItWorks.subtitleBusiness': 'Enterprise onboarding to gold-backed corporate treasury management.',
    
    // Personal Steps
    'howItWorks.personal.step1.title': 'Create Your Account',
    'howItWorks.personal.step1.description': 'Quick personal registration in minutes.',
    'howItWorks.personal.step2.title': 'Verify Your Identity',
    'howItWorks.personal.step2.description': 'Simple KYC verification process.',
    'howItWorks.personal.step3.title': 'Access Your Dashboard',
    'howItWorks.personal.step3.description': 'View your gold balance and transactions.',
    'howItWorks.personal.step4.title': 'Buy or Deposit Gold',
    'howItWorks.personal.step4.description': 'Purchase gold or deposit your existing holdings.',
    'howItWorks.personal.step5.title': 'Secure Storage',
    'howItWorks.personal.step5.description': 'Your gold safely stored in Swiss vaults.',
    'howItWorks.personal.step6.title': 'Use Your Gold',
    'howItWorks.personal.step6.description': 'Transfer, sell, or use for payments.',
    'howItWorks.personal.step7.title': 'Grow Your Wealth',
    'howItWorks.personal.step7.description': 'Earn returns with BNSL savings plans.',
    
    // Business Steps
    'howItWorks.business.step1.title': 'Register Your Company',
    'howItWorks.business.step1.description': 'Complete corporate onboarding with business documents.',
    'howItWorks.business.step2.title': 'Corporate KYC/AML',
    'howItWorks.business.step2.description': 'Full compliance verification for your organization.',
    'howItWorks.business.step3.title': 'Setup Team Access',
    'howItWorks.business.step3.description': 'Invite team members and assign roles & permissions.',
    'howItWorks.business.step4.title': 'Corporate Dashboard',
    'howItWorks.business.step4.description': 'Access enterprise analytics and treasury management.',
    'howItWorks.business.step5.title': 'Manage Corporate Gold',
    'howItWorks.business.step5.description': 'Deposit, custody, and manage company gold reserves.',
    'howItWorks.business.step6.title': 'Trade with FinaBridge',
    'howItWorks.business.step6.description': 'Connect with partners for gold-backed trade deals.',
    'howItWorks.business.step7.title': 'Treasury Optimization',
    'howItWorks.business.step7.description': 'Enterprise BNSL plans for corporate treasury growth.',
    
    // About Section
    'about.title': 'About Finatrades',
    'about.titleBusiness': 'Enterprise Solutions',
    'about.subtitle': 'Swiss-based fintech for personal gold-backed wealth management.',
    'about.subtitleBusiness': 'Institutional-grade gold infrastructure for modern businesses.',
    'about.vision': 'Our Vision',
    'about.visionBusiness': 'For Enterprise',
    'about.visionText': 'Build a new financial system where real assets drive stability.',
    'about.visionTextBusiness': 'Build your corporate treasury on gold-backed infrastructure with enterprise controls.',
    'about.mission': 'Our Mission',
    'about.missionBusiness': 'Key Benefits',
    
    // Mission Points Personal
    'about.personal.point1': 'Transparent access to gold',
    'about.personal.point2': 'Reliable storage and certification',
    'about.personal.point3': 'Modern, secure financial tools',
    'about.personal.point4': 'Personal wealth protection',
    'about.personal.point5': 'Simple, intuitive experience',
    
    // Mission Points Business
    'about.business.point1': 'Enterprise-grade infrastructure',
    'about.business.point2': 'Corporate compliance & governance',
    'about.business.point3': 'Global trade finance solutions',
    'about.business.point4': 'Multi-user corporate access',
    'about.business.point5': 'Institutional reporting standards',
    
    // Differentiators Personal
    'about.diff.personal.1.title': 'Swiss Operational Standards',
    'about.diff.personal.1.desc': 'Operating under strict Swiss regulatory framework.',
    'about.diff.personal.2.title': 'Real Vault-Backed Infrastructure',
    'about.diff.personal.2.desc': 'Every digital representation backed by physical gold.',
    'about.diff.personal.3.title': 'No Synthetic Assets',
    'about.diff.personal.3.desc': 'Real, physical gold only. No derivatives.',
    'about.diff.personal.4.title': 'Auditable Processes',
    'about.diff.personal.4.desc': 'Complete transparency with regular audits.',
    'about.diff.personal.5.title': 'Easy Gold Management',
    'about.diff.personal.5.desc': 'Simple buy, sell, and transfer operations.',
    'about.diff.personal.6.title': 'Wealth Growth Plans',
    'about.diff.personal.6.desc': 'Structured savings with guaranteed gold returns.',
    
    // Differentiators Business
    'about.diff.business.1.title': 'Enterprise Infrastructure',
    'about.diff.business.1.desc': 'Multi-user access, role management, and corporate controls.',
    'about.diff.business.2.title': 'Trade Finance Platform',
    'about.diff.business.2.desc': 'End-to-end importer/exporter deal management with FinaBridge.',
    'about.diff.business.3.title': 'Corporate Compliance',
    'about.diff.business.3.desc': 'Full regulatory compliance with enterprise-grade KYC/AML.',
    'about.diff.business.4.title': 'Global Settlement',
    'about.diff.business.4.desc': 'Cross-border B2B payments with gold-backed guarantees.',
    'about.diff.business.5.title': 'Team Management',
    'about.diff.business.5.desc': 'Invite team members with granular permission controls.',
    'about.diff.business.6.title': 'Enterprise Reporting',
    'about.diff.business.6.desc': 'Detailed analytics, audit trails, and financial reports.',
    
    // Swiss Standards
    'swiss.builtOn': 'Built on',
    'swiss.title': 'Swiss Financial',
    'swiss.titleHighlight': 'Standards',
    'swiss.description': 'Operating under strict Swiss regulations, Finatrades ensures security, compliance, and reliability for businesses worldwide.',
    'swiss.viewRegulatory': 'View Regulatory Information',
    
    // Contact Section
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Ready to start your gold-backed financial journey? Our team is here to help.',
    'contact.companyName': 'Finatrades Finance SA',
    'contact.companyDesc': 'Headquartered in Geneva, Switzerland — the global center of private banking.',
    'contact.address': 'Address',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.hours': 'Business Hours',
    'contact.hoursValue': 'Mon - Fri: 9:00 - 18:00 CET',
    'contact.formTitle': 'Send us a Message',
    'contact.fullName': 'Full Name',
    'contact.emailAddress': 'Email Address',
    'contact.company': 'Company',
    'contact.accountType': 'Account Type',
    'contact.selectType': 'Select type',
    'contact.individual': 'Individual',
    'contact.corporate': 'Corporate',
    'contact.importer': 'Importer',
    'contact.exporter': 'Exporter',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your needs...',
    'contact.sendMessage': 'Send Message',
    'contact.messageSent': 'Message Sent',
    'contact.messageConfirm': "We'll contact you within 24-48 hours.",
    'contact.sendAnother': 'Send Another Message',
    
    // Footer
    'footer.description': 'Swiss-regulated gold-backed digital finance platform. Building a new standard in asset-backed financial infrastructure.',
    'footer.products': 'Products',
    'footer.legal': 'Legal',
    'footer.quickLinks': 'Quick Links',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsConditions': 'Terms & Conditions',
    'footer.disclaimer': 'Disclaimer',
    'footer.copyright': '© {year} Finatrades Finance SA. All rights reserved.',
    
    // BNSL Page
    'bnsl.badge': "Buy 'N' SeLL Gold Plans",
    'bnsl.title': 'BNSL –',
    'bnsl.titleHighlight': 'Buy Now Sell Later',
    'bnsl.subtitle': 'Lock the worth of your physical gold into a structured plan with fixed pricing and secure buy back margin.',
    'bnsl.description': 'Finatrades BNSL lets you place the worth of your gold into a defined term, receive quarterly growth, and keep your principal safely stored in regulated vaults until maturity.',
    'bnsl.badge1': 'Swiss-Regulated Framework',
    'bnsl.badge2': 'Physical Gold • Vault Custody',
    'bnsl.badge3': 'Fixed Price • Quarterly Growth',
    'bnsl.startPlan': 'Start BNSL Plan',
    'bnsl.viewHow': 'View How It Works',
    'bnsl.vault.stage1': 'Your physical gold',
    'bnsl.vault.stage2': 'Allocated to BNSL Plan',
    'bnsl.vault.stage3': 'Stored in regulated vaults',
    'bnsl.vault.stage4': 'Principal gold worth locked until maturity',
    'bnsl.vault.locked': 'Gold Worth Locked & Secured',
    
    // BNSL Planner
    'bnsl.planner.badge': 'BNSL Gold Buy Back Planner',
              'bnsl.planner.title': 'BNSL Gold Buy Back',
    'bnsl.planner.titleHighlight': 'Planner',
    'bnsl.planner.subtitle': 'Plan your gold buy back and projected margins over time.',
    'bnsl.planner.formTitle': 'BNSL Gold Buy Back Planner',
              'bnsl.planner.formSubtitle': 'Plan your gold buy back and projected margins',
    'bnsl.planner.purchaseValue': 'BNSL Plan Value',
    'bnsl.planner.purchaseInfo': 'Total value of physical gold you buy and store in our vault.',
    'bnsl.planner.lockedPrice': 'Locked-In Gold Price (per gram)',
    'bnsl.planner.lockedPriceInfo': 'Price per gram on the day you start the plan.',
    'bnsl.planner.tenure': 'Plan Tenure',
    'bnsl.planner.additionRate': 'Estimated Gold Addition Rate',
    'bnsl.planner.perAnnum': 'per annum',
    'bnsl.planner.additionInfo': 'Annual estimate of additional gold added to your holding.',
    'bnsl.planner.projectionTitle': 'Gold Buy Back Projection',
    'bnsl.planner.projectionSubtitle': 'Based on your selected parameters',
    'bnsl.planner.purchasedValue': 'BNSL Plan Value',
              'bnsl.planner.purchasedValueSub': 'Initial plan value',
    'bnsl.planner.additionalValue': 'Additional Gold Value',
    'bnsl.planner.additionalValueSub': 'Projected gold additions',
    'bnsl.planner.totalValue': 'Total Gold Value',
    'bnsl.planner.totalValueSub': 'At end of term',
    'bnsl.planner.totalGrams': 'Total Gold (Grams)',
    'bnsl.planner.totalGramsSub': 'Physical gold owned',
    'bnsl.planner.disclaimer': 'Final cash value depends on the actual gold price at the time of selling. This projection is for planning purposes only.',
    'bnsl.planner.chartTitle': 'Gold Buy Back Over Time',
    'bnsl.planner.chartSubtitle': 'Projected value across the selected tenure',
    'bnsl.planner.timelineTitle': 'Quarterly Gold Addition Schedule',
    'bnsl.planner.timelineSub': 'Gold additions over your {tenure}-month plan',
    
    // BNSL Preview
    'bnsl.preview.title': 'Buy Now, Sell Later',
    'bnsl.preview.subtitle': 'Lock your gold purchase at today\'s price. Receive quarterly gold additions. Sell at maturity.',
    'bnsl.preview.months': 'months',
    'bnsl.preview.rate': 'rate',
    'bnsl.preview.returns': 'returns',
    'bnsl.preview.locked': 'LOCKED',
    'bnsl.preview.price': 'Price',
    
    // Why Finatrades
    'why.title': 'Why Choose Us',
    'why.swissRegulated': 'Swiss Regulated',
    'why.swissRegulatedDesc': 'Operating under strict Swiss financial regulations',
    'why.physicalGold': 'Physical Gold',
    'why.physicalGoldDesc': 'Real vault-stored gold, not paper derivatives',
    'why.secureVaults': 'Secure Vaults',
    'why.secureVaultsDesc': 'State-of-the-art vault facilities in Switzerland',
    'why.transparent': 'Transparent',
    'why.transparentDesc': 'Full visibility into your gold holdings',
    
    // Final CTA
    'cta.title': 'Ready to Get Started?',
    'cta.subtitle': 'Join thousands of users who trust Finatrades for gold-backed financial solutions.',
    'cta.button': 'Open Your Account',
    
    // Hero CTA
              'hero.cta.join': 'Join Us Now',
              'hero.cta.explorePersonal': 'Explore Personal Platform',
              'hero.cta.business': 'Business Transactions',

              // Common
              'common.learnMore': 'Learn More',
              'common.getStarted': 'Get Started',
              'common.backToHome': 'Back to Home',
              'common.loading': 'Loading...',

              // FinaVault Page
              'finavault.hero.badge': 'Secure Gold Custody',
              'finavault.hero.title': 'Fina',
              'finavault.hero.titleHighlight': 'Vault',
              'finavault.hero.subtitle': 'Your Digital Gold Reserve Vault',
              'finavault.hero.description': 'Store, track, verify and manage physical gold with secure, real-time vaulting technology. Backed by world-class vault providers and fully integrated with your FinaWallet.',
              'finavault.hero.cta1': 'Open Vault',
              'finavault.hero.cta2': 'View Certificate',
              'finavault.pillars.title': 'Institutional-Grade',
              'finavault.pillars.titleHighlight': 'Gold Storage',
              'finavault.pillars.1.title': 'Real Physical Gold',
              'finavault.pillars.1.desc': 'Your gold is stored in approved vaults with full insurance and audit trails.',
              'finavault.pillars.2.title': 'Digital Ownership Ledger',
              'finavault.pillars.2.desc': 'Real-time ledger tracking every gram with immutable records.',
              'finavault.pillars.3.title': 'Assay & Purity Verification',
              'finavault.pillars.3.desc': 'Every bar is assayed, numbered, and verified for 99.99% purity.',
              'finavault.pillars.4.title': 'Instant Wallet Integration',
              'finavault.pillars.4.desc': 'Your vault holdings sync instantly with your FinaPay Wallet.',
              'finavault.cert.title': 'Full Transparency,',
              'finavault.cert.titleHighlight': 'Every Gram Verified',
              'finavault.cert.description': 'Real certificates, live batch data, bar numbers, and storage details — all digitally accessible and cryptographically secured.',
              'finavault.operations.title': 'How',
              'finavault.operations.titleHighlight': 'Vaulting Works',
              'finavault.security.title': 'Bank-Level',
              'finavault.security.titleHighlight': 'Security',
              'finavault.security.description': 'Your gold is protected by multiple layers of physical and digital security, meeting the highest standards in the industry.',
              'finavault.cta.title': 'Secure Your Gold',
              'finavault.cta.titleHighlight': 'with Confidence',
              'finavault.cta.description': 'Manage physical gold on the world\'s most advanced digital vaulting platform.',
              'finavault.cta.button': 'Open Your Vault',

              // FinaPay Page
              'finapay.hero.badge': 'Digital Gold Wallet',
              'finapay.hero.title': 'Fina',
              'finapay.hero.titleHighlight': 'Pay',
              'finapay.hero.subtitle': 'Your Digital Gold Wallet for',
              'finapay.hero.subtitleHighlight': 'Payments, Storage & Transfers',
              'finapay.hero.description': 'Send, receive, store, and manage gold value instantly. Every wallet balance is backed by your physical gold stored securely in FinaVault.',
              'finapay.hero.cta1': 'Open Wallet',
              'finapay.hero.cta2': 'View Transactions',
              'finapay.features.title': 'Wallet',
              'finapay.features.titleHighlight': 'Features',
              'finapay.features.subtitle': 'A complete digital wallet experience powered by real gold',
              'finapay.wallet.title': 'A Wallet Built on',
              'finapay.wallet.titleHighlight': 'Real Gold',
              'finapay.wallet.subtitle': 'Intuitive interface designed for seamless gold transactions',
              'finapay.transfer.title': 'Instant Gold',
              'finapay.transfer.titleHighlight': 'Transfers',
              'finapay.transfer.subtitle': 'Move your gold value instantly between accounts or to other users',
              'finapay.network.title': 'Global Payment',
              'finapay.network.titleHighlight': 'Network',
              'finapay.network.subtitle': 'Instant cross-border gold payments across major financial hubs',
              'finapay.history.title': 'Transparent, Real-Time',
              'finapay.history.titleHighlight': 'Transaction Records',
              'finapay.history.subtitle': 'Every transaction is recorded, verified, and accessible',
              'finapay.security.title': 'High-Tech Gold',
              'finapay.security.titleHighlight': 'Security',
              'finapay.security.subtitle': 'Safe, compliant, and secure. Your gold is protected by enterprise-grade security.',
              'finapay.card.badge': 'Coming Soon',
              'finapay.card.title': 'A Premium Gold Card',
              'finapay.card.titleHighlight': 'Experience',
              'finapay.card.description': 'Spend your gold value anywhere with the FinaPay premium debit card. Seamlessly convert gold to fiat at the point of sale.',
              'finapay.card.cta': 'Join Waitlist',
              'finapay.cta.title': 'Your Gold. Your Wallet.',
              'finapay.cta.titleHighlight': 'Instantly Accessible.',
              'finapay.cta.subtitle': 'Empowering global payments backed by your own gold.',
              'finapay.cta.button': 'Open FinaPay Wallet',

              // FinaBridge Page
              'finabridge.hero.badge': 'Trade Bridge Platform',
              'finabridge.hero.title': 'Bridge Real Trade with',
              'finabridge.hero.titleHighlight': 'Verified Gold Worth',
              'finabridge.hero.subtitle': 'Use FinaBridge to connect importers and exporters through documented worth of physical gold, bringing stability and trust to cross-border deals.',
              'finabridge.hero.description': 'FinaBridge transforms physical gold into a settlement-ready financial instrument for real-world import and export flows.',
              'finabridge.hero.cta1': 'Open Corporate Account',
              'finabridge.hero.cta2': 'Talk to Trade Specialist',
              'finabridge.badges.1': 'Swiss-Regulated Framework',
              'finabridge.badges.2': 'Physical Gold • No Tokens',
              'finabridge.badges.3': 'Audit-Ready Documentation',

              // Final CTA
                        'finalcta.title': 'Experience the Future of',
                        'finalcta.titleHighlight': 'Gold-Backed Digital Finance',
                        'finalcta.subtitle': 'Open Your Finatrades Account Today',
                        'finalcta.button': 'Get Started',

                        // Product Suite
                        'productSuite.personal.label': 'Personal Tools',
                        'productSuite.personal.title': 'Your Tools to Manage Real Gold Digitally',
                        'productSuite.business.label': 'Business Ecosystem',
                        'productSuite.business.title': 'A Structured Ecosystem for High-Trust Business Transactions',
                        'productSuite.explore': 'Explore',

                        // Product Headlines & Descriptions (Business)
                        'productSuite.business.vault.headline': 'Deposit / Buy Gold',
                        'productSuite.business.vault.description': 'Get instant value and turn into a settlement financial instrument with your choice of hedging or floating strategies as your business grows.',
                        'productSuite.business.wallet.headline': 'Payments & Transfers',
                                  'productSuite.business.wallet.description': 'Send and receive payments through the platform, manage your wallet and spend anywhere using your gold-backed debit card.',
                        'productSuite.business.bridge.headline': 'Global Trade Monitoring',
                                  'productSuite.business.bridge.description': 'Monitor your **imports** and **exports** in real time, track gold-backed settlements and streamline every step of your cross-border business operations.',
                        'productSuite.business.bnsl.headline': "Buy 'N' SeLL Gold Plans",
                        'productSuite.business.bnsl.description': 'Get substantial margins and guaranteed returns thanks to our BNSL Plans.',

                        // Product Headlines & Bullets (Personal)
                        'productSuite.personal.vault.headline': 'Your Gold, Safely Stored',
                        'productSuite.personal.vault.bullet1': 'Deposit or buy gold instantly',
                        'productSuite.personal.vault.bullet2': 'Store your gold safely in approved vaults',
                        'productSuite.personal.vault.bullet3': 'Track your gold value in real time',
                        'productSuite.personal.vault.bullet4': 'Access full documentation anytime',
                        'productSuite.personal.wallet.headline': 'Gold at Your Fingertips',
                        'productSuite.personal.wallet.bullet1': 'Manage all your payments in one wallet',
                        'productSuite.personal.wallet.bullet2': 'Send & receive gold-backed transfers easily',
                        'productSuite.personal.wallet.bullet3': 'Spend using your debit card worldwide',
                        'productSuite.personal.wallet.bullet4': 'Deposit or withdraw cash whenever you need',
                        'productSuite.personal.bnsl.headline': 'Grow Your Gold Wealth',
                        'productSuite.personal.bnsl.bullet1': 'Buy or sell gold in seconds',
                        'productSuite.personal.bnsl.bullet2': 'Enjoy guaranteed profit margins',
                        'productSuite.personal.bnsl.bullet3': 'Access transparent, real-time pricing',
                        'productSuite.personal.bnsl.bullet4': 'Settle trades directly to your vault',

                        // BNSL How It Works
                        'bnslHowItWorks.badge': 'The Process',
                        'bnslHowItWorks.title': 'How',
                        'bnslHowItWorks.titleHighlight': 'BNSL',
                        'bnslHowItWorks.titleEnd': 'Works',
                        'bnslHowItWorks.cta': 'Estimate Your Gold Growth',
                        'bnslHowItWorks.step1.title': 'Purchase / Deposit Physical Gold',
                        'bnslHowItWorks.step1.desc': 'Your physical gold becomes the principal worth of your BNSL plan.',
                        'bnslHowItWorks.step2.title': 'Locked-In Price Established',
                        'bnslHowItWorks.step2.desc': 'Your gold\'s valuation is fixed for the entire duration of the plan.',
                        'bnslHowItWorks.step3.title': 'Choose Your Plan Tenure',
                        'bnslHowItWorks.step3.desc': 'Select from 12, 24, or 36 months.',
                        'bnslHowItWorks.step4.title': 'Quarterly Growth Credits',
                        'bnslHowItWorks.step4.desc': 'Every 3 months, additional gold value is added to your total worth.',
                        'bnslHowItWorks.step5.title': 'Buy Back at Maturity',
                        'bnslHowItWorks.step5.desc': 'Your gold remains protected until buy back at maturity.',
                        'bnslHowItWorks.step6.title': 'In-Kind Settlement',
                        'bnslHowItWorks.step6.desc': 'Your principal gold worth is returned based on the Locked-In Price.',

                        // BNSL Preview
                        'bnslPreview.badge': 'Structured BNSL Plans',
                        'bnslPreview.title': 'Buy Now, Sell Later',
                        'bnslPreview.subtitle': 'Fixed pricing, quarterly margins payout, and in-kind settlement',
                        'bnslPreview.mostPopular': 'Most Popular',
                        'bnslPreview.growth': 'p.a. growth in gold worth',
                        'bnslPreview.onGold': 'on 100g worth',
                        'bnslPreview.locked': 'LOCKED',
                        'bnslPreview.price': 'Price',

                        // BNSL Plan Comparison
                        'bnslPlan.badge': 'Plan Options',
                        'bnslPlan.title': 'Choose Your',
                        'bnslPlan.titleHighlight': 'BNSL Plan',
                        'bnslPlan.subtitle': 'Select the tenure that aligns with your gold accumulation goals.',
                        'bnslPlan.mostPopular': 'MOST POPULAR',
                        'bnslPlan.shortTerm': 'Short Term',
                        'bnslPlan.balanced': 'Balanced',
                        'bnslPlan.longTerm': 'Long Term',
                        'bnslPlan.shortDesc': 'Shorter duration',
                        'bnslPlan.balancedDesc': 'Medium duration',
                        'bnslPlan.longDesc': 'Highest projected growth',
                        'bnslPlan.growthRate': 'p.a. growth in gold worth',
                        'bnslPlan.growthCycles': 'Growth Cycles',
                        'bnslPlan.quarters': 'quarters',
                        'bnslPlan.select': 'Select',
                        'bnslPlan.months': 'Month Plan',
                        'bnslPlan.feature1.12': 'Indicative ~10% growth p.a.',
                        'bnslPlan.feature2.12': '4 quarterly growth cycles',
                        'bnslPlan.feature3.12': 'Returned worth based on Locked-In Price',
                        'bnslPlan.feature4.12': 'Ideal for near-term goals',
                        'bnslPlan.feature1.24': 'Indicative ~11% growth p.a.',
                        'bnslPlan.feature2.24': '8 quarterly growth cycles',
                        'bnslPlan.feature3.24': 'Ideal for stable medium-term goals',
                        'bnslPlan.feature4.24': 'Most popular choice',
                        'bnslPlan.feature1.36': 'Indicative ~12% growth p.a.',
                        'bnslPlan.feature2.36': '12 quarterly growth cycles',
                        'bnslPlan.feature3.36': 'Designed for long-term accumulation',
                        'bnslPlan.feature4.36': 'Maximum growth potential',

                        // BNSL Benefits
                        'bnslBenefits.badge': 'Key Benefits',
                        'bnslBenefits.title': 'Why Users Prefer the',
                        'bnslBenefits.titleHighlight': 'BNSL Plan',
                        'bnslBenefits.benefit1.title': 'Physical Gold Security',
                        'bnslBenefits.benefit1.desc': 'Your investment remains fully backed by physical gold held in regulated vaults.',
                        'bnslBenefits.benefit2.title': 'Fixed Price Stability',
                        'bnslBenefits.benefit2.desc': 'The Locked-In Price safeguards your valuation throughout the plan.',
                        'bnslBenefits.benefit3.title': 'Quarterly Gold Growth Credits',
                        'bnslBenefits.benefit3.desc': 'Your gold worth increases every 3 months based on the agreed rate.',
                        'bnslBenefits.benefit4.title': 'In-Kind Settlement',
                                  'bnslBenefits.benefit4.desc': 'At maturity, your principal worth is returned in gold, not cash.',

                                  // Why Finatrades
                                  'whyFinatrades.badge': 'Why Choose Us',
                                  'whyFinatrades.title': 'The Finatrades Advantage',
                                  'whyFinatrades.feature1.label': 'Trust & Compliance',
                                  'whyFinatrades.feature1.desc': 'Swiss regulatory standards',
                                  'whyFinatrades.feature2.label': 'Instant Gold Liquidity',
                                  'whyFinatrades.feature2.desc': 'Convert and transfer instantly',
                                  'whyFinatrades.feature3.label': 'Real Physical Assets',
                                  'whyFinatrades.feature3.desc': 'No synthetic derivatives',
                                  'whyFinatrades.feature4.label': 'Corporate Trade Solutions',
                                  'whyFinatrades.feature4.desc': 'B2B gold settlements',
                                  'whyFinatrades.feature5.label': 'Secure Cross-Border Utility',
                                  'whyFinatrades.feature5.desc': 'Global gold transfers',
                                  'whyFinatrades.feature6.label': 'Enterprise-Grade UI',
                                  'whyFinatrades.feature6.desc': 'Institutional experience',

                                  // BNSL FAQ
                                  'bnslFaq.badge': 'Questions',
                                  'bnslFaq.title': 'Frequently Asked',
                                  'bnslFaq.titleHighlight': 'Questions',
                                  'bnslFaq.q1': 'What is the Locked-In Price?',
                                  'bnslFaq.a1': 'It is the fixed valuation applied to your gold at the start of your plan. All growth and settlement calculations use this fixed price.',
                                  'bnslFaq.q2': 'How is growth added?',
                                  'bnslFaq.a2': 'Growth is calculated based on your principal gold worth and credited every 3 months.',
                                  'bnslFaq.q3': 'What happens at maturity?',
                                  'bnslFaq.a3': 'Your full principal gold worth is returned to your FinaWallet within 3 business days.',
                                  'bnslFaq.q4': 'Can I exit early?',
                                  'bnslFaq.a4': 'Yes, but penalties apply and your returned gold worth will be reduced.',
                                  'bnslFaq.q5': 'Do I receive cash?',
                                  'bnslFaq.a5': 'No. All payments and settlement are made in the form of gold worth.',

                                  // BNSL Risk Disclosure
                                  'bnslRisk.title': 'Risk Disclosure',
                                  'bnslRisk.subtitle': 'Important information to consider',
                                  'bnslRisk.risk1': 'Early termination may reduce your final gold worth.',
                                  'bnslRisk.risk2': 'Locked-In Price limits upside benefits from rising gold prices.',
                                  'bnslRisk.risk3': 'All growth is credited in gold worth only.',
                                  'bnslRisk.risk4': 'The plan depends on counterparty performance.',
                                  'bnslRisk.risk5': 'Please read full Terms & Conditions before joining.',

                                            // BNSL Final CTA
                                            'bnslFinalCta.title1': 'Start Your BNSL',
                                            'bnslFinalCta.title2': 'Gold Plan Today',
                                            'bnslFinalCta.subtitle': 'Lock your gold worth at a fixed price and grow it quarterly.',
                                            'bnslFinalCta.startPlan': 'Start BNSL Plan',
                                            'bnslFinalCta.support': 'Speak with Support',
                                                    },
  
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.finavault': 'FinaVault',
    'nav.finapay': 'FinaPay',
    'nav.finabridge': 'FinaBridge',
    'nav.bnsl': 'BNSL',
    'nav.joinUs': 'À Propos de Nous',
    'nav.personal': 'Personnel',
    'nav.business': 'Entreprise',
    
    // Hero Section
    'hero.finatrades': 'Finatrades',
    'hero.personal.title': "L'Or Numérique, Conçu pour Tous",
    'hero.personal.subtitle': "Épargnez, stockez et utilisez la valeur réelle de l'or via un compte en ligne sécurisé et moderne.",
    'hero.personal.description': "Finatrades vous donne le pouvoir de l'or — envoyez, recevez, dépensez partout, et gagnez plus grâce au BNSL. Optionnel : Rejoignez les plans B'N'SL structurés — verrouillez l'or dans des plans de rachat structurés pour des durées définies.",
    'hero.personal.cta1': 'À Propos de Nous',
    'hero.personal.cta2': 'Créer un Compte Finatrades',
    'hero.business.title': "Infrastructure Financière Réglementée Adossée à l'Or",
    'hero.business.subtitle': 'Conçu pour les entreprises, importateurs, exportateurs, maisons de négoce et partenaires institutionnels.',
    'hero.business.description': "Grâce à un partenariat stratégique avec Wingold et Metals DMCC, Finatrades transforme l'or physique en instruments financiers prêts pour le règlement.",
    'hero.business.cta1': 'À Propos de Nous',
    'hero.business.cta2': 'Créer un Compte Finatrades',
    'hero.swissRegulated': 'Plateforme Réglementée Suisse',
    
    // Products
    'products.title': 'Nos Produits',
    'products.subtitle': "Une suite complète d'outils financiers adossés à l'or",
    'products.explore': 'Explorer',
    
    // Personal Products
    'products.personal.finavault.name': 'FinaVault',
    'products.personal.finavault.tagline': 'Coffre-Fort Personnel',
    'products.personal.finavault.description': "Un registre numérique sécurisé affichant votre or stocké, certificats et détails de pureté.",
    'products.personal.finapay.name': 'FinaPay Portefeuille',
    'products.personal.finapay.tagline': "Vue Valeur de l'Or",
    'products.personal.finapay.description': "Affiche votre or en grammes et valeur estimée. Aide à planifier dépenses et épargne.",
    'products.personal.bnsl.name': 'FinaEarn (BNSL)',
    'products.personal.bnsl.tagline': 'Plans de Rachat',
    'products.personal.bnsl.description': 'Choisissez des durées définies (12, 24 ou 36 mois) pour un rachat structuré.',
    
    // Business Products
    'products.business.finavault.name': 'FinaVault Entreprise',
    'products.business.finavault.tagline': "Registre des Réserves d'Or",
    'products.business.finavault.description': "Visibilité complète sur les numéros de lingots, origines, pureté et emplacements des coffres.",
    'products.business.finapay.name': 'FinaPay Business',
    'products.business.finapay.tagline': "Tableau de Bord Opérationnel",
    'products.business.finapay.description': "Suivi en temps réel de la valeur pour la trésorerie, surveillance des risques et allocation.",
    'products.business.finabridge.name': 'FinaBridge',
    'products.business.finabridge.tagline': "Couche Support Commercial",
    'products.business.finabridge.description': "Documentation et flux de travail pour les transactions commerciales adossées à l'or.",
    'products.business.bnsl.name': 'FinaEarn (BNSL)',
    'products.business.bnsl.tagline': 'Rachat Programmé',
    'products.business.bnsl.description': "Verrouillez l'or dans des termes structurés alignés sur les cycles commerciaux.",
    
    // How It Works
    'howItWorks.title': 'Comment ça fonctionne',
    'howItWorks.titleBusiness': 'Comment ça fonctionne pour les Entreprises',
    'howItWorks.subtitle': "Un parcours simple de la création de compte à la richesse adossée à l'or.",
    'howItWorks.subtitleBusiness': "Intégration entreprise vers la gestion de trésorerie adossée à l'or.",
    
    // Personal Steps
    'howItWorks.personal.step1.title': 'Créez Votre Compte',
    'howItWorks.personal.step1.description': 'Inscription personnelle rapide en quelques minutes.',
    'howItWorks.personal.step2.title': 'Vérifiez Votre Identité',
    'howItWorks.personal.step2.description': 'Processus de vérification KYC simple.',
    'howItWorks.personal.step3.title': 'Accédez à Votre Tableau de Bord',
    'howItWorks.personal.step3.description': "Consultez votre solde d'or et vos transactions.",
    'howItWorks.personal.step4.title': "Achetez ou Déposez de l'Or",
    'howItWorks.personal.step4.description': "Achetez de l'or ou déposez vos avoirs existants.",
    'howItWorks.personal.step5.title': 'Stockage Sécurisé',
    'howItWorks.personal.step5.description': 'Votre or stocké en toute sécurité dans des coffres suisses.',
    'howItWorks.personal.step6.title': 'Utilisez Votre Or',
    'howItWorks.personal.step6.description': 'Transférez, vendez ou utilisez pour les paiements.',
    'howItWorks.personal.step7.title': 'Faites Croître Votre Patrimoine',
    'howItWorks.personal.step7.description': "Gagnez des rendements avec les plans d'épargne BNSL.",
    
    // Business Steps
    'howItWorks.business.step1.title': 'Enregistrez Votre Entreprise',
    'howItWorks.business.step1.description': "Intégration d'entreprise avec documents commerciaux.",
    'howItWorks.business.step2.title': 'KYC/AML Entreprise',
    'howItWorks.business.step2.description': 'Vérification de conformité complète pour votre organisation.',
    'howItWorks.business.step3.title': "Configurez l'Accès Équipe",
    'howItWorks.business.step3.description': 'Invitez les membres et attribuez rôles et permissions.',
    'howItWorks.business.step4.title': 'Tableau de Bord Entreprise',
    'howItWorks.business.step4.description': 'Accédez aux analyses et à la gestion de trésorerie.',
    'howItWorks.business.step5.title': "Gérez l'Or de l'Entreprise",
    'howItWorks.business.step5.description': "Déposez, gardez et gérez les réserves d'or de l'entreprise.",
    'howItWorks.business.step6.title': 'Commercez avec FinaBridge',
    'howItWorks.business.step6.description': "Connectez-vous avec des partenaires pour des transactions adossées à l'or.",
    'howItWorks.business.step7.title': 'Optimisation de Trésorerie',
    'howItWorks.business.step7.description': "Plans BNSL entreprise pour la croissance de la trésorerie.",
    
    // About Section
    'about.title': 'À Propos de Finatrades',
    'about.titleBusiness': 'Solutions Entreprise',
    'about.subtitle': "Fintech suisse pour la gestion de patrimoine adossée à l'or.",
    'about.subtitleBusiness': "Infrastructure or de qualité institutionnelle pour les entreprises modernes.",
    'about.vision': 'Notre Vision',
    'about.visionBusiness': 'Pour les Entreprises',
    'about.visionText': 'Construire un nouveau système financier où les actifs réels assurent la stabilité.',
    'about.visionTextBusiness': "Construisez votre trésorerie d'entreprise sur une infrastructure adossée à l'or avec des contrôles d'entreprise.",
    'about.mission': 'Notre Mission',
    'about.missionBusiness': 'Avantages Clés',
    
    // Mission Points Personal
    'about.personal.point1': "Accès transparent à l'or",
    'about.personal.point2': 'Stockage et certification fiables',
    'about.personal.point3': 'Outils financiers modernes et sécurisés',
    'about.personal.point4': 'Protection du patrimoine personnel',
    'about.personal.point5': 'Expérience simple et intuitive',
    
    // Mission Points Business
    'about.business.point1': "Infrastructure de niveau entreprise",
    'about.business.point2': 'Conformité et gouvernance d\'entreprise',
    'about.business.point3': 'Solutions de financement commercial mondial',
    'about.business.point4': 'Accès multi-utilisateurs entreprise',
    'about.business.point5': 'Normes de reporting institutionnelles',
    
    // Differentiators Personal
    'about.diff.personal.1.title': 'Normes Opérationnelles Suisses',
    'about.diff.personal.1.desc': 'Opérant sous un cadre réglementaire suisse strict.',
    'about.diff.personal.2.title': 'Infrastructure Adossée aux Coffres',
    'about.diff.personal.2.desc': "Chaque représentation numérique adossée à de l'or physique.",
    'about.diff.personal.3.title': 'Pas d\'Actifs Synthétiques',
    'about.diff.personal.3.desc': 'Or physique réel uniquement. Pas de dérivés.',
    'about.diff.personal.4.title': 'Processus Auditables',
    'about.diff.personal.4.desc': 'Transparence complète avec des audits réguliers.',
    'about.diff.personal.5.title': "Gestion Facile de l'Or",
    'about.diff.personal.5.desc': 'Opérations simples d\'achat, vente et transfert.',
    'about.diff.personal.6.title': 'Plans de Croissance',
    'about.diff.personal.6.desc': "Épargne structurée avec rendements or garantis.",
    
    // Differentiators Business
    'about.diff.business.1.title': 'Infrastructure Entreprise',
    'about.diff.business.1.desc': 'Accès multi-utilisateurs, gestion des rôles et contrôles.',
    'about.diff.business.2.title': 'Plateforme Finance Commerce',
    'about.diff.business.2.desc': 'Gestion complète import/export avec FinaBridge.',
    'about.diff.business.3.title': 'Conformité Entreprise',
    'about.diff.business.3.desc': 'Conformité réglementaire complète avec KYC/AML entreprise.',
    'about.diff.business.4.title': 'Règlement Mondial',
    'about.diff.business.4.desc': "Paiements B2B transfrontaliers avec garanties adossées à l'or.",
    'about.diff.business.5.title': 'Gestion d\'Équipe',
    'about.diff.business.5.desc': 'Invitez des membres avec contrôles de permissions granulaires.',
    'about.diff.business.6.title': 'Reporting Entreprise',
    'about.diff.business.6.desc': 'Analyses détaillées, pistes d\'audit et rapports financiers.',
    
    // Swiss Standards
    'swiss.builtOn': 'Construit sur',
    'swiss.title': 'Normes Financières',
    'swiss.titleHighlight': 'Suisses',
    'swiss.description': 'Opérant sous des réglementations suisses strictes, Finatrades assure sécurité, conformité et fiabilité pour les entreprises du monde entier.',
    'swiss.viewRegulatory': 'Voir les Informations Réglementaires',
    
    // Contact Section
    'contact.title': 'Contactez-nous',
    'contact.subtitle': "Prêt à commencer votre parcours financier adossé à l'or ? Notre équipe est là pour vous aider.",
    'contact.companyName': 'Finatrades Finance SA',
    'contact.companyDesc': 'Siège à Genève, Suisse — le centre mondial de la banque privée.',
    'contact.address': 'Adresse',
    'contact.email': 'Email',
    'contact.phone': 'Téléphone',
    'contact.hours': 'Heures d\'Ouverture',
    'contact.hoursValue': 'Lun - Ven: 9:00 - 18:00 CET',
    'contact.formTitle': 'Envoyez-nous un Message',
    'contact.fullName': 'Nom Complet',
    'contact.emailAddress': 'Adresse Email',
    'contact.company': 'Entreprise',
    'contact.accountType': 'Type de Compte',
    'contact.selectType': 'Sélectionner le type',
    'contact.individual': 'Individuel',
    'contact.corporate': 'Entreprise',
    'contact.importer': 'Importateur',
    'contact.exporter': 'Exportateur',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Parlez-nous de vos besoins...',
    'contact.sendMessage': 'Envoyer le Message',
    'contact.messageSent': 'Message Envoyé',
    'contact.messageConfirm': 'Nous vous contacterons dans les 24-48 heures.',
    'contact.sendAnother': 'Envoyer un Autre Message',
    
    // Footer
    'footer.description': "Plateforme financière numérique adossée à l'or réglementée en Suisse. Construire une nouvelle norme d'infrastructure financière adossée aux actifs.",
    'footer.products': 'Produits',
    'footer.legal': 'Juridique',
    'footer.quickLinks': 'Liens Rapides',
    'footer.privacyPolicy': 'Politique de Confidentialité',
    'footer.termsConditions': 'Conditions Générales',
    'footer.disclaimer': 'Avertissement',
    'footer.copyright': '© {year} Finatrades Finance SA. Tous droits réservés.',
    
    // BNSL Page
    'bnsl.badge': 'Plans Achat et Vente d\'Or',
    'bnsl.title': 'BNSL –',
    'bnsl.titleHighlight': 'Achetez Maintenant Vendez Plus Tard',
    'bnsl.subtitle': "Verrouillez la valeur de votre or physique dans un plan structuré avec un prix fixe et une marge de rachat sécurisée.",
    'bnsl.description': "Finatrades BNSL vous permet de placer la valeur de votre or dans un terme défini, de recevoir une croissance trimestrielle et de garder votre principal stocké en toute sécurité dans des coffres réglementés jusqu'à l'échéance.",
    'bnsl.badge1': 'Cadre Réglementé Suisse',
    'bnsl.badge2': 'Or Physique • Garde en Coffre',
    'bnsl.badge3': 'Prix Fixe • Croissance Trimestrielle',
    'bnsl.startPlan': 'Démarrer un Plan BNSL',
    'bnsl.viewHow': 'Voir Comment Ça Marche',
    'bnsl.vault.stage1': 'Votre or physique',
    'bnsl.vault.stage2': 'Alloué au Plan BNSL',
    'bnsl.vault.stage3': 'Stocké dans des coffres réglementés',
    'bnsl.vault.stage4': "Valeur de l'or principal verrouillée jusqu'à l'échéance",
    'bnsl.vault.locked': "Valeur de l'Or Verrouillée et Sécurisée",
    
    // BNSL Planner
    'bnsl.planner.badge': "Planificateur de Rachat d'Or BNSL",
              'bnsl.planner.title': "Rachat d'Or BNSL",
    'bnsl.planner.titleHighlight': 'Planificateur',
    'bnsl.planner.subtitle': "Planifiez votre rachat d'or et les marges projetées dans le temps.",
    'bnsl.planner.formTitle': "Planificateur de Rachat d'Or BNSL",
              'bnsl.planner.formSubtitle': "Planifiez votre rachat d'or et les marges projetées",
    'bnsl.planner.purchaseValue': "Valeur du Plan BNSL",
    'bnsl.planner.purchaseInfo': "Valeur totale de l'or physique que vous achetez et stockez dans notre coffre.",
    'bnsl.planner.lockedPrice': "Prix de l'Or Verrouillé (par gramme)",
    'bnsl.planner.lockedPriceInfo': 'Prix par gramme le jour où vous démarrez le plan.',
    'bnsl.planner.tenure': 'Durée du Plan',
    'bnsl.planner.additionRate': "Taux d'Addition d'Or Estimé",
    'bnsl.planner.perAnnum': 'par an',
    'bnsl.planner.additionInfo': "Estimation annuelle de l'or supplémentaire ajouté à votre détention.",
    'bnsl.planner.projectionTitle': "Projection de Rachat d'Or",
    'bnsl.planner.projectionSubtitle': 'Basé sur vos paramètres sélectionnés',
    'bnsl.planner.purchasedValue': "Valeur du Plan BNSL",
              'bnsl.planner.purchasedValueSub': "Valeur initiale du plan",
    'bnsl.planner.additionalValue': "Valeur de l'Or Supplémentaire",
    'bnsl.planner.additionalValueSub': "Ajouts d'or projetés",
    'bnsl.planner.totalValue': "Valeur Totale de l'Or",
    'bnsl.planner.totalValueSub': 'À la fin du terme',
    'bnsl.planner.totalGrams': 'Or Total (Grammes)',
    'bnsl.planner.totalGramsSub': 'Or physique possédé',
    'bnsl.planner.disclaimer': "La valeur finale en espèces dépend du prix réel de l'or au moment de la vente. Cette projection est à des fins de planification uniquement.",
    'bnsl.planner.chartTitle': "Rachat d'Or dans le Temps",
    'bnsl.planner.chartSubtitle': 'Valeur projetée sur la durée sélectionnée',
    'bnsl.planner.timelineTitle': "Calendrier d'Addition Trimestrielle d'Or",
    'bnsl.planner.timelineSub': "Ajouts d'or sur votre plan de {tenure} mois",
    
    // BNSL Preview
    'bnsl.preview.title': 'Achetez Maintenant, Vendez Plus Tard',
    'bnsl.preview.subtitle': "Verrouillez votre achat d'or au prix d'aujourd'hui. Recevez des ajouts d'or trimestriels. Vendez à l'échéance.",
    'bnsl.preview.months': 'mois',
    'bnsl.preview.rate': 'taux',
    'bnsl.preview.returns': 'rendements',
    'bnsl.preview.locked': 'VERROUILLÉ',
    'bnsl.preview.price': 'Prix',
    
    // Why Finatrades
    'why.title': 'Pourquoi Nous Choisir',
    'why.swissRegulated': 'Réglementé Suisse',
    'why.swissRegulatedDesc': 'Opérant sous des réglementations financières suisses strictes',
    'why.physicalGold': 'Or Physique',
    'why.physicalGoldDesc': "Or réel stocké en coffre, pas de dérivés papier",
    'why.secureVaults': 'Coffres Sécurisés',
    'why.secureVaultsDesc': 'Installations de coffres de pointe en Suisse',
    'why.transparent': 'Transparent',
    'why.transparentDesc': "Visibilité complète sur vos avoirs en or",
    
    // Final CTA
    'cta.title': 'Prêt à Commencer ?',
    'cta.subtitle': "Rejoignez des milliers d'utilisateurs qui font confiance à Finatrades pour des solutions financières adossées à l'or.",
    'cta.button': 'Ouvrez Votre Compte',
    
    // Hero CTA
              'hero.cta.join': 'Rejoignez-nous',
              'hero.cta.explorePersonal': 'Explorer la Plateforme',
              'hero.cta.business': 'Transactions Entreprise',

              // Common
              'common.learnMore': 'En Savoir Plus',
              'common.getStarted': 'Commencer',
              'common.backToHome': "Retour à l'Accueil",
              'common.loading': 'Chargement...',

              // FinaVault Page
              'finavault.hero.badge': "Garde d'Or Sécurisée",
              'finavault.hero.title': 'Fina',
              'finavault.hero.titleHighlight': 'Vault',
              'finavault.hero.subtitle': "Votre Coffre-Fort Numérique de Réserve d'Or",
              'finavault.hero.description': "Stockez, suivez, vérifiez et gérez l'or physique avec une technologie de coffre-fort sécurisée en temps réel. Soutenu par des fournisseurs de coffres-forts de classe mondiale et entièrement intégré à votre FinaWallet.",
              'finavault.hero.cta1': 'Ouvrir le Coffre',
              'finavault.hero.cta2': 'Voir le Certificat',
              'finavault.pillars.title': 'Stockage d\'Or',
              'finavault.pillars.titleHighlight': 'de Qualité Institutionnelle',
              'finavault.pillars.1.title': "Or Physique Réel",
              'finavault.pillars.1.desc': "Votre or est stocké dans des coffres approuvés avec assurance complète et pistes d'audit.",
              'finavault.pillars.2.title': 'Registre de Propriété Numérique',
              'finavault.pillars.2.desc': 'Suivi en temps réel de chaque gramme avec des enregistrements immuables.',
              'finavault.pillars.3.title': 'Vérification de Pureté et Essai',
              'finavault.pillars.3.desc': 'Chaque lingot est analysé, numéroté et vérifié pour une pureté de 99,99%.',
              'finavault.pillars.4.title': 'Intégration Instantanée au Portefeuille',
              'finavault.pillars.4.desc': 'Vos avoirs de coffre se synchronisent instantanément avec votre Portefeuille FinaPay.',
              'finavault.cert.title': 'Transparence Totale,',
              'finavault.cert.titleHighlight': 'Chaque Gramme Vérifié',
              'finavault.cert.description': "Certificats réels, données de lots en direct, numéros de lingots et détails de stockage — le tout accessible numériquement et sécurisé cryptographiquement.",
              'finavault.operations.title': 'Comment',
              'finavault.operations.titleHighlight': 'Fonctionne le Coffre',
              'finavault.security.title': 'Sécurité',
              'finavault.security.titleHighlight': 'Niveau Bancaire',
              'finavault.security.description': "Votre or est protégé par plusieurs couches de sécurité physique et numérique, répondant aux normes les plus élevées de l'industrie.",
              'finavault.cta.title': 'Sécurisez Votre Or',
              'finavault.cta.titleHighlight': 'en Toute Confiance',
              'finavault.cta.description': "Gérez l'or physique sur la plateforme de coffre-fort numérique la plus avancée au monde.",
              'finavault.cta.button': 'Ouvrez Votre Coffre',

              // FinaPay Page
              'finapay.hero.badge': "Portefeuille d'Or Numérique",
              'finapay.hero.title': 'Fina',
              'finapay.hero.titleHighlight': 'Pay',
              'finapay.hero.subtitle': "Votre Portefeuille d'Or Numérique pour",
              'finapay.hero.subtitleHighlight': 'Paiements, Stockage et Transferts',
              'finapay.hero.description': "Envoyez, recevez, stockez et gérez la valeur de l'or instantanément. Chaque solde de portefeuille est adossé à votre or physique stocké en toute sécurité dans FinaVault.",
              'finapay.hero.cta1': 'Ouvrir le Portefeuille',
              'finapay.hero.cta2': 'Voir les Transactions',
              'finapay.features.title': 'Fonctionnalités',
              'finapay.features.titleHighlight': 'du Portefeuille',
              'finapay.features.subtitle': "Une expérience de portefeuille numérique complète alimentée par de l'or réel",
              'finapay.wallet.title': 'Un Portefeuille Construit sur',
              'finapay.wallet.titleHighlight': "de l'Or Réel",
              'finapay.wallet.subtitle': "Interface intuitive conçue pour des transactions d'or fluides",
              'finapay.transfer.title': "Transferts d'Or",
              'finapay.transfer.titleHighlight': 'Instantanés',
              'finapay.transfer.subtitle': "Déplacez instantanément votre valeur d'or entre comptes ou vers d'autres utilisateurs",
              'finapay.network.title': 'Réseau de Paiement',
              'finapay.network.titleHighlight': 'Mondial',
              'finapay.network.subtitle': "Paiements d'or transfrontaliers instantanés à travers les principaux centres financiers",
              'finapay.history.title': 'Enregistrements de Transactions',
              'finapay.history.titleHighlight': 'Transparents et en Temps Réel',
              'finapay.history.subtitle': 'Chaque transaction est enregistrée, vérifiée et accessible',
              'finapay.security.title': "Sécurité de l'Or",
              'finapay.security.titleHighlight': 'Haute Technologie',
              'finapay.security.subtitle': "Sûr, conforme et sécurisé. Votre or est protégé par une sécurité de niveau entreprise.",
              'finapay.card.badge': 'Bientôt Disponible',
              'finapay.card.title': 'Une Expérience de Carte Or',
              'finapay.card.titleHighlight': 'Premium',
              'finapay.card.description': "Dépensez votre valeur d'or n'importe où avec la carte de débit premium FinaPay. Convertissez l'or en monnaie fiduciaire au point de vente.",
              'finapay.card.cta': "Rejoindre la Liste d'Attente",
              'finapay.cta.title': 'Votre Or. Votre Portefeuille.',
              'finapay.cta.titleHighlight': 'Accessible Instantanément.',
              'finapay.cta.subtitle': "Des paiements mondiaux soutenus par votre propre or.",
              'finapay.cta.button': 'Ouvrir le Portefeuille FinaPay',

              // FinaBridge Page
              'finabridge.hero.badge': 'Plateforme de Pont Commercial',
              'finabridge.hero.title': 'Reliez le Commerce Réel avec',
              'finabridge.hero.titleHighlight': "une Valeur d'Or Vérifiée",
              'finabridge.hero.subtitle': "Utilisez FinaBridge pour connecter importateurs et exportateurs grâce à la valeur documentée de l'or physique, apportant stabilité et confiance aux transactions transfrontalières.",
              'finabridge.hero.description': "FinaBridge transforme l'or physique en instrument financier prêt pour le règlement des flux d'import et d'export réels.",
              'finabridge.hero.cta1': 'Ouvrir un Compte Entreprise',
              'finabridge.hero.cta2': 'Parler à un Spécialiste Commercial',
              'finabridge.badges.1': 'Cadre Réglementé Suisse',
              'finabridge.badges.2': 'Or Physique • Pas de Tokens',
              'finabridge.badges.3': 'Documentation Prête pour l\'Audit',

              // Final CTA
                                  'finalcta.title': "Découvrez l'Avenir de la",
                                  'finalcta.titleHighlight': "Finance Numérique Adossée à l'Or",
                                  'finalcta.subtitle': 'Ouvrez Votre Compte Finatrades Aujourd\'hui',
                                  'finalcta.button': 'Commencer',

                        // Product Suite
                        'productSuite.personal.label': 'Outils Personnels',
                        'productSuite.personal.title': 'Vos Outils pour Gérer l\'Or Réel Numériquement',
                        'productSuite.business.label': 'Écosystème Business',
                        'productSuite.business.title': 'Un Écosystème Structuré pour des Transactions Commerciales de Haute Confiance',
                        'productSuite.explore': 'Explorer',

                        // Product Headlines & Descriptions (Business)
                        'productSuite.business.vault.headline': 'Dépôt / Achat d\'Or',
                        'productSuite.business.vault.description': 'Obtenez une valeur instantanée et transformez-la en instrument financier de règlement avec votre choix de stratégies de couverture ou flottantes à mesure que votre entreprise se développe.',
                        'productSuite.business.wallet.headline': 'Paiements et Transferts',
                                  'productSuite.business.wallet.description': 'Envoyez et recevez des paiements via la plateforme, gérez votre portefeuille et dépensez partout avec votre carte de débit adossée à l\'or.',
                        'productSuite.business.bridge.headline': 'Surveillance du Commerce Mondial',
                                  'productSuite.business.bridge.description': 'Surveillez vos **importations** et **exportations** en temps réel, suivez les règlements adossés à l\'or et simplifiez chaque étape de vos opérations commerciales transfrontalières.',
                        'productSuite.business.bnsl.headline': "Plans Achat 'N' VeNTE d'Or",
                        'productSuite.business.bnsl.description': 'Obtenez des marges substantielles et des rendements garantis grâce à nos Plans BNSL.',

                        // Product Headlines & Bullets (Personal)
                        'productSuite.personal.vault.headline': 'Votre Or, Stocké en Sécurité',
                        'productSuite.personal.vault.bullet1': 'Déposez ou achetez de l\'or instantanément',
                        'productSuite.personal.vault.bullet2': 'Stockez votre or en toute sécurité dans des coffres agréés',
                        'productSuite.personal.vault.bullet3': 'Suivez la valeur de votre or en temps réel',
                        'productSuite.personal.vault.bullet4': 'Accédez à la documentation complète à tout moment',
                        'productSuite.personal.wallet.headline': 'L\'Or à Portée de Main',
                        'productSuite.personal.wallet.bullet1': 'Gérez tous vos paiements dans un seul portefeuille',
                        'productSuite.personal.wallet.bullet2': 'Envoyez et recevez des transferts adossés à l\'or facilement',
                        'productSuite.personal.wallet.bullet3': 'Dépensez avec votre carte de débit partout dans le monde',
                        'productSuite.personal.wallet.bullet4': 'Déposez ou retirez de l\'argent quand vous en avez besoin',
                        'productSuite.personal.bnsl.headline': 'Faites Croître Votre Patrimoine en Or',
                        'productSuite.personal.bnsl.bullet1': 'Achetez ou vendez de l\'or en quelques secondes',
                        'productSuite.personal.bnsl.bullet2': 'Profitez de marges bénéficiaires garanties',
                        'productSuite.personal.bnsl.bullet3': 'Accédez à des prix transparents en temps réel',
                        'productSuite.personal.bnsl.bullet4': 'Réglez les transactions directement dans votre coffre',

                        // BNSL How It Works
                        'bnslHowItWorks.badge': 'Le Processus',
                        'bnslHowItWorks.title': 'Comment',
                        'bnslHowItWorks.titleHighlight': 'BNSL',
                        'bnslHowItWorks.titleEnd': 'Fonctionne',
                        'bnslHowItWorks.cta': 'Estimez Votre Croissance en Or',
                        'bnslHowItWorks.step1.title': 'Achetez / Déposez de l\'Or Physique',
                        'bnslHowItWorks.step1.desc': 'Votre or physique devient la valeur principale de votre plan BNSL.',
                        'bnslHowItWorks.step2.title': 'Prix Verrouillé Établi',
                        'bnslHowItWorks.step2.desc': 'La valorisation de votre or est fixée pour toute la durée du plan.',
                        'bnslHowItWorks.step3.title': 'Choisissez Votre Durée',
                        'bnslHowItWorks.step3.desc': 'Sélectionnez entre 12, 24 ou 36 mois.',
                        'bnslHowItWorks.step4.title': 'Crédits de Croissance Trimestriels',
                        'bnslHowItWorks.step4.desc': 'Tous les 3 mois, une valeur or supplémentaire est ajoutée à votre total.',
                        'bnslHowItWorks.step5.title': 'Rachat à l\'Échéance',
                        'bnslHowItWorks.step5.desc': 'Votre or reste protégé jusqu\'au rachat à l\'échéance.',
                        'bnslHowItWorks.step6.title': 'Règlement en Nature',
                        'bnslHowItWorks.step6.desc': 'Votre valeur principale en or est retournée selon le Prix Verrouillé.',

                        // BNSL Preview
                        'bnslPreview.badge': 'Plans BNSL Structurés',
                        'bnslPreview.title': 'Achetez Maintenant, Vendez Plus Tard',
                        'bnslPreview.subtitle': 'Prix fixes, paiement trimestriel des marges et règlement en nature',
                        'bnslPreview.mostPopular': 'Le Plus Populaire',
                        'bnslPreview.growth': 'croissance p.a. en valeur or',
                        'bnslPreview.onGold': 'sur 100g de valeur',
                        'bnslPreview.locked': 'VERROUILLÉ',
                        'bnslPreview.price': 'Prix',

                        // BNSL Plan Comparison
                        'bnslPlan.badge': 'Options de Plan',
                        'bnslPlan.title': 'Choisissez Votre',
                        'bnslPlan.titleHighlight': 'Plan BNSL',
                        'bnslPlan.subtitle': 'Sélectionnez la durée qui correspond à vos objectifs d\'accumulation d\'or.',
                        'bnslPlan.mostPopular': 'LE PLUS POPULAIRE',
                        'bnslPlan.shortTerm': 'Court Terme',
                        'bnslPlan.balanced': 'Équilibré',
                        'bnslPlan.longTerm': 'Long Terme',
                        'bnslPlan.shortDesc': 'Durée plus courte',
                        'bnslPlan.balancedDesc': 'Durée moyenne',
                        'bnslPlan.longDesc': 'Croissance projetée la plus élevée',
                        'bnslPlan.growthRate': 'croissance p.a. en valeur or',
                        'bnslPlan.growthCycles': 'Cycles de Croissance',
                        'bnslPlan.quarters': 'trimestres',
                        'bnslPlan.select': 'Sélectionner le Plan',
                        'bnslPlan.months': 'Mois',
                        'bnslPlan.feature1.12': 'Croissance indicative ~10% p.a.',
                        'bnslPlan.feature2.12': '4 cycles de croissance trimestriels',
                        'bnslPlan.feature3.12': 'Valeur retournée selon le Prix Verrouillé',
                        'bnslPlan.feature4.12': 'Idéal pour les objectifs à court terme',
                        'bnslPlan.feature1.24': 'Croissance indicative ~11% p.a.',
                        'bnslPlan.feature2.24': '8 cycles de croissance trimestriels',
                        'bnslPlan.feature3.24': 'Idéal pour des objectifs stables à moyen terme',
                        'bnslPlan.feature4.24': 'Choix le plus populaire',
                        'bnslPlan.feature1.36': 'Croissance indicative ~12% p.a.',
                        'bnslPlan.feature2.36': '12 cycles de croissance trimestriels',
                        'bnslPlan.feature3.36': 'Conçu pour l\'accumulation à long terme',
                        'bnslPlan.feature4.36': 'Potentiel de croissance maximum',

                        // BNSL Benefits
                        'bnslBenefits.badge': 'Avantages Clés',
                        'bnslBenefits.title': 'Pourquoi les Utilisateurs Préfèrent le',
                        'bnslBenefits.titleHighlight': 'Plan BNSL',
                        'bnslBenefits.benefit1.title': 'Sécurité de l\'Or Physique',
                        'bnslBenefits.benefit1.desc': 'Votre investissement reste entièrement adossé à de l\'or physique détenu dans des coffres réglementés.',
                        'bnslBenefits.benefit2.title': 'Stabilité du Prix Fixe',
                        'bnslBenefits.benefit2.desc': 'Le Prix Verrouillé protège votre valorisation tout au long du plan.',
                        'bnslBenefits.benefit3.title': 'Crédits de Croissance Trimestriels',
                        'bnslBenefits.benefit3.desc': 'Votre valeur en or augmente tous les 3 mois selon le taux convenu.',
                        'bnslBenefits.benefit4.title': 'Règlement en Nature',
                                  'bnslBenefits.benefit4.desc': 'À l\'échéance, votre valeur principale est retournée en or, pas en espèces.',

                                  // Why Finatrades
                                  'whyFinatrades.badge': 'Pourquoi Nous Choisir',
                                  'whyFinatrades.title': 'L\'Avantage Finatrades',
                                  'whyFinatrades.feature1.label': 'Confiance et Conformité',
                                  'whyFinatrades.feature1.desc': 'Normes réglementaires suisses',
                                  'whyFinatrades.feature2.label': 'Liquidité Or Instantanée',
                                  'whyFinatrades.feature2.desc': 'Convertissez et transférez instantanément',
                                  'whyFinatrades.feature3.label': 'Actifs Physiques Réels',
                                  'whyFinatrades.feature3.desc': 'Pas de dérivés synthétiques',
                                  'whyFinatrades.feature4.label': 'Solutions Commerce B2B',
                                  'whyFinatrades.feature4.desc': 'Règlements or B2B',
                                  'whyFinatrades.feature5.label': 'Utilité Transfrontalière',
                                  'whyFinatrades.feature5.desc': 'Transferts or mondiaux',
                                  'whyFinatrades.feature6.label': 'Interface Entreprise',
                                  'whyFinatrades.feature6.desc': 'Expérience institutionnelle',

                                  // BNSL FAQ
                                  'bnslFaq.badge': 'Questions',
                                  'bnslFaq.title': 'Questions',
                                  'bnslFaq.titleHighlight': 'Fréquentes',
                                  'bnslFaq.q1': 'Qu\'est-ce que le Prix Verrouillé ?',
                                  'bnslFaq.a1': 'C\'est la valorisation fixe appliquée à votre or au début de votre plan. Tous les calculs de croissance et de règlement utilisent ce prix fixe.',
                                  'bnslFaq.q2': 'Comment la croissance est-elle ajoutée ?',
                                  'bnslFaq.a2': 'La croissance est calculée sur la base de votre valeur principale en or et créditée tous les 3 mois.',
                                  'bnslFaq.q3': 'Que se passe-t-il à l\'échéance ?',
                                  'bnslFaq.a3': 'Votre valeur principale complète en or est retournée à votre FinaWallet dans les 3 jours ouvrables.',
                                  'bnslFaq.q4': 'Puis-je sortir plus tôt ?',
                                  'bnslFaq.a4': 'Oui, mais des pénalités s\'appliquent et votre valeur or retournée sera réduite.',
                                  'bnslFaq.q5': 'Est-ce que je reçois de l\'argent ?',
                                  'bnslFaq.a5': 'Non. Tous les paiements et règlements sont effectués sous forme de valeur or.',

                                  // BNSL Risk Disclosure
                                  'bnslRisk.title': 'Divulgation des Risques',
                                  'bnslRisk.subtitle': 'Informations importantes à considérer',
                                  'bnslRisk.risk1': 'La résiliation anticipée peut réduire votre valeur or finale.',
                                  'bnslRisk.risk2': 'Le Prix Verrouillé limite les avantages en cas de hausse des prix de l\'or.',
                                  'bnslRisk.risk3': 'Toute la croissance est créditée uniquement en valeur or.',
                                  'bnslRisk.risk4': 'Le plan dépend de la performance de la contrepartie.',
                                  'bnslRisk.risk5': 'Veuillez lire les Conditions Générales complètes avant de rejoindre.',

                                            // BNSL Final CTA
                                            'bnslFinalCta.title1': 'Commencez Votre Plan',
                                            'bnslFinalCta.title2': 'BNSL Or Aujourd\'hui',
                                            'bnslFinalCta.subtitle': 'Verrouillez votre valeur or à un prix fixe et faites-la croître trimestriellement.',
                                            'bnslFinalCta.startPlan': 'Démarrer un Plan BNSL',
                                            'bnslFinalCta.support': 'Parler au Support',
                                                    }
                                                  };

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    try {
      const stored = localStorage.getItem('finatrades_language');
      if (stored === 'en' || stored === 'fr') {
        setLanguage(stored);
      }
    } catch (e) {}
  }, []);

  useEffect(() => {
    try {
      localStorage.setItem('finatrades_language', language);
    } catch (e) {}
  }, [language]);

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || translations['en']?.[key] || key;
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return { language: 'en', setLanguage: () => {}, t: (key) => key };
  }
  return context;
}

export default LanguageContext;